name: .NET Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0

    - name: Restore dependencies
      run: dotnet restore CrossLangChat/CrossLangChat.csproj  # Path to your main app project file

    - name: Build and test
      run: dotnet test CrossLangChat.Test/CrossLangChat.Test.csproj  # Path to your test project file